# -*- coding: utf-8 -*-
"""Lista_CDM_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CN8lh2IcEwUsdou_fYIcqC_Lvra2guqG
"""

#Lista Exercício 01 - Introdução ao python
#Cheat Sheet - Python Basics  
#Por: Yoshi
#Data: Jan/2020

#Principais bibliotecas
import pandas as pd   # liguagem R
import numpy as np    # linguagem Matlab
from matplotlib import pyplot as plt   # gráficos

#%%01) Operações matemáticas
x=5
x+2
x-2
x*2
x**2
x%2
x/float(2)
#%%02) Formato dos dados

y1='5'            # string   (menssagem ou texto)
y2=5              # integer  (inteiro)  
y3=5.0            # float(flutuante, ou decimal)
y4=bool('True')   # boolean (logico) 

#%%03) Fazer uma list e indexar

a = 'is'
b = 'nice'
my_list = ['my', 'list', a, b]

my_list[0]
my_list[3]
my_list[0:3]
my_list[0:4]
my_list[1:4]
my_list[-1]


#%%04) Manipular uma list

my_list.index(a)
my_list.count(a)
my_list.append('!')
my_list.remove('!')
del(my_list[0:1])
my_list.pop(0)
my_list.insert(1,'yo')
my_list.sort()

# lista de duas dimensoes
my_list2 = [[4,5,6,7], [3,4,5,6]]
my_list2[1][:2]

#%%05)  Fazer um array , manupular e operar

my_list=[1,2,3,4]
my_list2 = [[4,5,6,7], [3,4,5,6]]

my_array=np.array(my_list)
my_array2=np.array(my_list2)

my_array[1]
my_array.shape
np.append([1,2,3],[5,6,7])
np.insert(my_array, 1, 5)
np.delete(my_array,[1])
np.mean(my_array)
np.median(my_array)
np.std(my_array)


##% FIM